#222 Refactor: TastingNoteConverter 에서 toTastingNoteResponseDTO 삭제
Drink-Easy/backend pull request #223
Opened 2024-11-26 11:21 UTC by jeongyeon0208

2024-11-26 11:22 UTC, jeongyeon0208 commented on src/main/java/com/drinkeg/drinkeg/tastingNote/domain/TastingNote.java
- 필요없는 updateWine 매서드 삭제
- updateTasteDate 코드 컨벤션 안맞는 것 수정

2024-11-27 01:33 UTC, jeongyun1206 requested changes

2024-11-27 01:33 UTC, jeongyun1206 commented on src/main/java/com/drinkeg/drinkeg/converter/TastingNoteConverter.java
단순히 엔티티를 생성하는 과정도 도메인에서 처리하는게 좋아보입니다.
컨버터를 아예 사용하지 않는 방향으로  수정하는게 좋아보입니다.

2024-11-27 07:24 UTC, jeongyeon0208 commented on src/main/java/com/drinkeg/drinkeg/converter/TastingNoteConverter.java
- TastingNoteConverter 사용하지 않게 수정 완료했습니다.

2024-12-02 05:42 UTC, merged