#231 Refactor: 와인 정보, 리뷰 보기 수정
Drink-Easy/backend pull request #232
Opened 2024-12-15 14:30 UTC by jeongyeon0208

- 와인정보, 리뷰에 좋아요 반영 완료
- 리뷰 정렬 기준 별점순 반영 완료

2024-12-18 04:26 UTC, jeongyun1206 commented on src/main/java/com/drinkeg/drinkeg/wine/repository/WineRepositoryImpl.java
Liked를 체크하는 로직이 다른 메서드로 분리되는게 srp에 더 부합할 것 같습니다.

service 계층에서 와인 리뷰들을 한번에 가져온 다음에, setLiked와 같은 도메인 로직으로 liked를 처리해주는게 더 나아보입니다.

2024-12-20 14:57 UTC, jeongyun1206 requested changes

2024-12-20 14:57 UTC, jeongyun1206 commented on src/main/java/com/drinkeg/drinkeg/wine/repository/WineRepositoryImpl.java
Optional을 사용하는 이유가 nullPointerExceptioin을 방지하기 위해서인데, 조회된 와인 리뷰가 없으면 null값을 반환하는 로직은 적합하지 않아보입니다.

조회되는 와인이 없는경우, 빈 리스트를 반환하도록 변경하는 것이 보안상 좋을것 같습니다.

return recentReviews.orElse(null); 이부분 수정 요청 드립니다.

2024-12-26 11:29 UTC, jeongyeon0208 reviewed
- getTastingNoteNoseListByUsername(회원의 NoseList 정보 가져올 때)
- showMemberNoseMapList(사용자가 작성한 TastingNoteNose 리스트 가져올 때)
- findWineResponseByWineId(최근 생성된 tastingNoteList 불러올 때)

위 세 부분에서 Optional 없을 때 isEmpty() 결과 true(즉 null이 아님) 나오는 것 확인하여 Optional이 불필요해 삭제했습니다.

2024-12-26 11:34 UTC, merged